# Generated by Django 4.2.7 on 2025-09-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "prescriptions",
            "0003_prescription_diagnosis_prescription_filled_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="diagnosis",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="prescription_id",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
