# Generated by Django 4.2.7 on 2025-09-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescriptions", "0004_alter_prescription_diagnosis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="prescription_id",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
